{% set version = "0.9.3" %}

package:
  name: r-taxize
  version: {{ version }}

source:
  fn: taxize_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/taxize_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/taxize/taxize_{{ version }}.tar.gz
  sha256: ece4737a6dc052d66858487c125f21b8186430ca85680790da801065f6839416

build:
  number: 1
  script: R CMD INSTALL --build .
  merge_build_host: True  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-ape
    - r-bold >=0.3.5
    - r-crul >=0.4.0
    - r-data.table
    - r-foreach
    - r-httr >=1.2.1
    - r-jsonlite
    - r-natserv >=0.1.4
    - r-plyr
    - r-reshape2
    - r-ritis >=0.5.0
    - r-rotl >=3.0.0
    - r-rredlist >=0.3.0
    - r-stringr
    - r-tibble >=1.2
    - r-wikitaxa >=0.1.4
    - r-worrms >=0.1.0
    - r-xml2 >=1.0.0
    - r-zoo
  run:
    - r-base
    - r-ape
    - r-bold >=0.3.5
    - r-crul >=0.4.0
    - r-data.table
    - r-foreach
    - r-httr >=1.2.1
    - r-jsonlite
    - r-natserv >=0.1.4
    - r-plyr
    - r-reshape2
    - r-ritis >=0.5.0
    - r-rotl >=3.0.0
    - r-rredlist >=0.3.0
    - r-stringr
    - r-tibble >=1.2
    - r-wikitaxa >=0.1.4
    - r-worrms >=0.1.0
    - r-xml2 >=1.0.0
    - r-zoo

test:
  commands:
    - $R -e "library('taxize')"  # [not win]
    - "\"%R%\" -e \"library('taxize')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/taxizes
  license: MIT
  license_file: LICENSE
  summary: Interacts with a suite of web 'APIs' for taxonomic tasks, such as getting database
    specific taxonomic identifiers, verifying species names, getting taxonomic hierarchies,
    fetching downstream and upstream taxonomic names, getting taxonomic synonyms, converting
    scientific to common names and vice versa, and more.

extra:
  recipe-maintainers:
    - dpryan79
    - ocefpaf
