{% set version = "0.9.100" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-taxize
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/taxize_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/taxize/taxize_{{ version }}.tar.gz
  sha256: e2e578fc45eb5d1306332892c67535fa4bc32d63129532df2c6cde393993cd29

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-r6
    - r-ape
    - r-bold >=0.8.6
    - r-cli
    - r-conditionz
    - r-crayon
    - r-crul >=0.7.0
    - r-data.table
    - r-foreach
    - r-jsonlite
    - r-natserv >=1.0.0
    - r-phangorn
    - r-ritis >=0.7.6
    - r-rotl >=3.0.0
    - r-rredlist >=0.5.0
    - r-tibble >=1.2
    - r-wikitaxa >=0.3.0
    - r-worrms >=0.4.0
    - r-xml2 >=1.2.0
    - r-zoo
  run:
    - r-base
    - r-r6
    - r-ape
    - r-bold >=0.8.6
    - r-cli
    - r-conditionz
    - r-crayon
    - r-crul >=0.7.0
    - r-data.table
    - r-foreach
    - r-jsonlite
    - r-natserv >=1.0.0
    - r-phangorn
    - r-ritis >=0.7.6
    - r-rotl >=3.0.0
    - r-rredlist >=0.5.0
    - r-tibble >=1.2
    - r-wikitaxa >=0.3.0
    - r-worrms >=0.4.0
    - r-xml2 >=1.2.0
    - r-zoo

test:
  commands:
    - $R -e "library('taxize')"           # [not win]
    - "\"%R%\" -e \"library('taxize')\""  # [win]

about:
  home: https://github.com/ropensci/taxize (devel), https://taxize.dev (user manual)
  license: MIT
  summary: Interacts with a suite of web 'APIs' for taxonomic tasks, such as getting database specific taxonomic identifiers, verifying species names, getting taxonomic hierarchies, fetching downstream and upstream taxonomic names, getting taxonomic synonyms, converting scientific to common names and vice versa, and more.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf

# Package: taxize
# Title: Taxonomic Information from Around the Web
# Description: Interacts with a suite of web 'APIs' for taxonomic tasks, such as getting database specific taxonomic identifiers, verifying species names, getting taxonomic hierarchies, fetching downstream and upstream taxonomic names, getting taxonomic synonyms, converting scientific to common names and vice versa, and more.
# Version: 0.9.97
# License: MIT + file LICENSE
# URL: https://docs.ropensci.org/taxize (website), https://github.com/ropensci/taxize (devel), https://taxize.dev (user manual)
# BugReports: https://github.com/ropensci/taxize/issues
# Authors@R: c(person(given = "Scott", family = "Chamberlain", role = c("aut", "cre"), email = "myrmecocystus@gmail.com", comment = c(ORCID = "0000-0003-1444-9135")), person(given = "Eduard", family = "Szoecs", role = "aut"), person(given = "Zachary", family = "Foster", role = "aut"), person(given = "Zebulun", family = "Arendsee", role = "aut"), person(given = "Carl", family = "Boettiger", role = "ctb"), person(given = "Karthik", family = "Ram", role = "ctb"), person(given = "Ignasi", family = "Bartomeus", role = "ctb"), person(given = "John", family = "Baumgartner", role = "ctb"), person(given = "James", family = "O'Donnell", role = "ctb"), person(given = "Jari", family = "Oksanen", role = "ctb"), person(given = "Bastian Greshake", family = "Tzovaras", role = "ctb"), person(given = "Philippe", family = "Marchand", role = "ctb"), person(given = "Vinh", family = "Tran", role = "ctb"), person(given = "Maelle", family = "Salmon", role = "ctb"), person(given = "Gaopeng", family = "Li", role = "ctb"), person(given = "Matthias", family = "Grenie", role = "ctb"), person(given = "rOpenSci", role = "fnd", comment = "https://ropensci.org/"))
# LazyLoad: yes
# LazyData: true
# VignetteBuilder: knitr
# Encoding: UTF-8
# Language: en-US
# Depends: R(>= 3.2.1)
# Imports: graphics, methods, stats, utils, crul (>= 0.7.0), xml2 (>= 1.2.0), jsonlite, foreach, ape, zoo, data.table, tibble (>= 1.2), bold (>= 0.8.6), rredlist (>= 0.5.0), rotl (>= 3.0.0), ritis (>= 0.7.6), worrms (>= 0.4.0), natserv (>= 1.0.0), wikitaxa (>= 0.3.0), R6, crayon, cli, phangorn, conditionz
# Suggests: testthat, knitr, rmarkdown, vegan, vcr
# RoxygenNote: 7.1.0
# X-schema.org-applicationCategory: Taxonomy
# X-schema.org-keywords: taxonomy, biology, nomenclature, JSON, API, web, api-client, identifiers, species, names
# X-schema.org-isPartOf: https://ropensci.org
# NeedsCompilation: no
# Packaged: 2020-06-09 05:31:58 UTC; sckott
# Author: Scott Chamberlain [aut, cre] (<https://orcid.org/0000-0003-1444-9135>), Eduard Szoecs [aut], Zachary Foster [aut], Zebulun Arendsee [aut], Carl Boettiger [ctb], Karthik Ram [ctb], Ignasi Bartomeus [ctb], John Baumgartner [ctb], James O'Donnell [ctb], Jari Oksanen [ctb], Bastian Greshake Tzovaras [ctb], Philippe Marchand [ctb], Vinh Tran [ctb], Maelle Salmon [ctb], Gaopeng Li [ctb], Matthias Grenie [ctb], rOpenSci [fnd] (https://ropensci.org/)
# Maintainer: Scott Chamberlain <myrmecocystus@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-06-09 06:00:02 UTC
