# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "vjd4VZxb7OX3nEz2bCVcLMcyYJczAmgef/Rb5+o+BgCB6AkWi7mLrE92kvgSovlOvW3uXP50uzKtwm+hCfkzQl70k5DIDoNxXIC+NtlOIphtQ27DwuaAetA2ewMCjw2+ZTxaf3mLuPs2bmwsuO5tTelAp8a3oZrpmCBB+HJIEk3j7589I7urBm1Ew7y47/MWZTAU/FsKjAYxRhpIoVftBhQZFIZZrOyBkDW6C+jBORRjKuLzWIyaCgd+BUK5w2oUM5pJ14E4nD2afkpeu9QvZt4x4wMsQB0awwI30qSisOE3ysZd4kzXWDZF4PfdUYTt5cQknsoosqXzjtrGKHcrutzGcFBufadv+r5VwVvhx9ewbKX8kvPnfkvNkZhKwgDUyvbRvH4wdhzIuct1rc16iV086Wp5En5+h/g/p4zjXJ8/SoLBVle0KMZlvt6/KEazAHQAugk/3e+o1Al/LKsuRvM6G/P7zU8iHXeFZHUPNOATW/g4lAahqbl9Xe/ZfukWU5IvniMM8NBUO/Q6euURONP2w1cQaWj3plmt7wThnIWM1rR6OKQb2nQsd0eU5oMeppfZxTiOE7mcTu5xO0VKhBYpVMVhtzPPIQq7R6LKGQ4/P+Q8JUOogUlUWefuqdXtRu3SkT+Or+fSClZ3cTVtB7eNRneRiBR8+/cGjHorOLQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
