appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: tIxEwgJeLFV2ARjdMuH7WqfM1H75Q2LCCzUChF8mpmjGzsBLsn5kJaiytLeY6EqvqWzyH8IRWqAo6xMeqQnttXgRiLYYnQNKE4SZj3AimqF2LJAk+4cm6qNtABiXahQipfpb/Bdd8w52nAuxYonEXb+x4bfslLvWb8Z35ZPBeL0avCfzM+oP1mET8Dk/++96T/1jqmf4K9wFx5Awe0QV8LngiB2FqvMyc58TlL6OHw4C3fhRArodX5o1+PTsF/4Ie4nHEOeCm41cxX16lp+MByGFjJuzEmJjfyi+REUDRtL5ydq0OoX3O4X9o9wC77vNviaLbiIA2++9ApPd023iAf9+KUJutySyDMd0MH06dZGIEHeMg7LulxXIgjSIcGu25wzX8kiRtEpEZmACUCQIpZ+94X9WJ5LE7gyP/B/TIkUBwebQhhh9K/HAXo5woJXm40+iIOb+cYjsApl3x41KQXLl8h6cdKLY0JOKSfzu13aCujVGoOduPaM8dRx57PwtUX8vGlrYcYBDlHM/a4eBTIgcdN6V6uIJ3dBng8eP3MpV+923ILo1MOBg95DhR8kVwlCiIlXfrxgkzaMMeZwkFDmBXHnEz69XxVwBHLZVE3+N38pDq1W44c4akYZaHUdxn1SswcfoRGJWbd/Pqaj36WgjVvrVSTM1FcBPRftBgnw=}
